/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

/**
 *
 * @author Administrator
 */
public class dashBoardPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashBoardPage
     */
    public dashBoardPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashbody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dashbody1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        dashbody.setBackground(new java.awt.Color(255, 255, 204));
        dashbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/logo-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 180, 120));

        dashbody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 160, 130));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("SCHOLARSHIP TRACKING APP");
        dashbody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 370, 50));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("POBLACION, WARD II, MINGLANILLA, CEBU,PHILIPPINES");
        dashbody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 380, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/icons8-back-arrow-26.png"))); // NOI18N
        dashbody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        getContentPane().add(dashbody);
        dashbody.setBounds(0, 0, 690, 130);

        dashbody1.setBackground(new java.awt.Color(255, 0, 0));
        dashbody1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/icons8-automatic-100.png"))); // NOI18N
        dashbody1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 170, 140));

        jButton1.setBackground(new java.awt.Color(204, 0, 0,80));
        jButton1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton1.setText("SETTINGS");
        dashbody1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 110, -1));

        getContentPane().add(dashbody1);
        dashbody1.setBounds(0, 130, 690, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashbody;
    private javax.swing.JPanel dashbody1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
