/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarship.tracking;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }
     Color navcolor=new Color(204,204,0);
    Color headcolor=new Color(255,0,0);
    Color bodycolor=new Color(255,255,204);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        dashPane = new javax.swing.JPanel();
        dashName = new javax.swing.JLabel();
        settingspane = new javax.swing.JPanel();
        settingsName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maindesktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        body1 = new javax.swing.JPanel();
        navbar1 = new javax.swing.JPanel();
        dashPane1 = new javax.swing.JPanel();
        dashName1 = new javax.swing.JLabel();
        settingspane1 = new javax.swing.JPanel();
        settingsName1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();
        maindesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 420));
        getContentPane().setLayout(null);

        body.setBackground(new java.awt.Color(255, 255, 204));
        body.setLayout(null);

        navbar.setBackground(new java.awt.Color(204, 204, 0));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashPane.setBackground(new java.awt.Color(204, 204, 0));
        dashPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashPaneMouseExited(evt);
            }
        });
        dashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashName.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        dashName.setText("DASH BOARD");
        dashPane.add(dashName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        navbar.add(dashPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 50));

        settingspane.setBackground(new java.awt.Color(204, 204, 0));
        settingspane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingspaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingspaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingspaneMouseExited(evt);
            }
        });
        settingspane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsName.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        settingsName.setText("SETTINGS");
        settingspane.add(settingsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        navbar.add(settingspane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/logo-removebg-preview.png"))); // NOI18N
        navbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 110));

        body.add(navbar);
        navbar.setBounds(0, 0, 160, 420);

        header.setBackground(new java.awt.Color(255, 0, 0));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/icons8-close-26.png"))); // NOI18N
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/icons8-subtract-26.png"))); // NOI18N
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        body.add(header);
        header.setBounds(160, 0, 600, 60);

        maindesktopPane.setBackground(new java.awt.Color(255, 255, 204));
        maindesktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maindesktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/scholarbackground3.jpg"))); // NOI18N
        maindesktopPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 320));

        body1.setBackground(new java.awt.Color(255, 255, 204));
        body1.setLayout(null);

        navbar1.setBackground(new java.awt.Color(204, 204, 0));
        navbar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashPane1.setBackground(new java.awt.Color(204, 204, 0));
        dashPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashName1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        dashName1.setText("DASH BOARD");
        dashPane1.add(dashName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        navbar1.add(dashPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 50));

        settingspane1.setBackground(new java.awt.Color(204, 204, 0));
        settingspane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsName1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        settingsName1.setText("SETTINGS");
        settingspane1.add(settingsName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        navbar1.add(settingspane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/logo-removebg-preview.png"))); // NOI18N
        navbar1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 110));

        body1.add(navbar1);
        navbar1.setBounds(0, 0, 160, 420);

        header1.setBackground(new java.awt.Color(204, 0, 0));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body1.add(header1);
        header1.setBounds(160, 0, 600, 60);

        maindesktopPane1.setBackground(new java.awt.Color(255, 255, 204));
        maindesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImageFolder/scholarbackground3.jpg"))); // NOI18N
        maindesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 320));

        body1.add(maindesktopPane1);
        maindesktopPane1.setBounds(160, 60, 600, 360);

        maindesktopPane.add(body1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        maindesktopPane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        body.add(maindesktopPane);
        maindesktopPane.setBounds(160, 60, 600, 360);

        getContentPane().add(body);
        body.setBounds(0, 0, 760, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashPaneMouseClicked

    private void dashPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseEntered
      dashPane.setBackground(bodycolor);
    }//GEN-LAST:event_dashPaneMouseEntered

    private void dashPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseExited
       dashPane.setBackground(navcolor);
    }//GEN-LAST:event_dashPaneMouseExited

    private void settingspaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingspaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_settingspaneMouseClicked

    private void settingspaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingspaneMouseEntered
      settingspane.setBackground(bodycolor);
    }//GEN-LAST:event_settingspaneMouseEntered

    private void settingspaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingspaneMouseExited
       settingspane.setBackground(navcolor);
    }//GEN-LAST:event_settingspaneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body1;
    private javax.swing.JLabel dashName;
    private javax.swing.JLabel dashName1;
    private javax.swing.JPanel dashPane;
    private javax.swing.JPanel dashPane1;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane maindesktopPane;
    private javax.swing.JDesktopPane maindesktopPane1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel navbar1;
    private javax.swing.JLabel settingsName;
    private javax.swing.JLabel settingsName1;
    private javax.swing.JPanel settingspane;
    private javax.swing.JPanel settingspane1;
    // End of variables declaration//GEN-END:variables
}
